### PR TITLE
ISSUE-110  Fix default thumbnail size and fix used pictures

### LINKED ISSUE #110: Wrong image sizes (blog detail page)
Hi Christopher,

we use your blog plugin and we are very happy with it. But when it comes to image resizing and thumbnails it has a strange behaviour.

First of all there is only one default thumbnail size (650px) for blog teaser images after installation (src/SasBlogModule.php):

```php
        $mediaFolderRepository->create([
            [
                'entity' => BlogEntriesDefinition::ENTITY_NAME,
                'associationFields' => ['media'],
                'folder' => [
                    'name' => 'Blog Images',
                    'useParentConfiguration' => false,
                    'configuration' => [
                        'createThumbnails' => true,
                        'mediaThumbnailSizes' => [
                            [
                                'width' => 650,
                                'height' => 330,
                            ],
                        ],
                    ],
                ],
            ],
        ], $context);
```

But the default width of images on blog detail page using default Storefront theme is 893.33px. So the images don't look good:

image

So we have to adjust the generated thumbnails... So I went with 308px (for blog listing) and 893px (for detail page):

image

But after I changed it, it's getting worse.... because the desktop version now uses the 308px version (firefox is used):

image

I guess something is misconfigured in this part of code (src/Resources/views/storefront/element/cms-element-blog-detail.html.twig):

```twig
                            {% sw_thumbnails 'blog-image-teaser' with {
                                    media: element.data.media,
                                    sizes: {
                                    'xs': '501px',
                                    'sm': '315px',
                                    'md': '427px',
                                    'lg': '333px',
                                    'xl': '284px'
                                }
                            } %}
```

Why this template uses small images on `xl` and large images on `xs`? After resizing the window to a smaller viewport I will see the sharp version (893px) of the image:

image

Proposals:
* Add two versions of thumbnails in SasBlogModule.php (one for listing, one for teaser)
* Use only large images in src/Resources/views/storefront/element/cms-element-blog-detail.html.twig (maybe smaller thumbnails version on very small viewports)

But it would be even better, if you could configure those sizes.

### PR DESCRIPTION
**Pull request by timonf**
What I did:

* Fixed default image size (kept aspect ratio, increased image quality, added more sizes).
* I guess there were 2 sizes intended: 330px and 650px. I kept them and also added 900 and 1280px. Each aspect ratio is 16:9 (330px in width means 185px in height).

Fixes #110

### CODE REVIEW

**Review by viennt — APPROVED** [review]

**Comment by viennt** [comment]
@hungmac-sw Please review this PR when you are available. Thank you.

**Review by hungmac-sw — APPROVED** [review]

**Comment by viennt** [comment]
Hi @timonf , please update the change log files too, and then we can merge this PR. Thanks.

**Comment by timonf** [comment]
> Hi @timonf , please update the change log files too, and then we can merge this PR. Thanks.

@viennt Below 1.5.8 section or as a new 1.5.9 section? I see 1.5.8 is already tagged, so I would go with 1.5.9

**Comment by viennt** [comment]
> @viennt Below 1.5.8 section or as a new 1.5.9 section? I see 1.5.8 is already tagged, so I would go with 1.5.9

@timonf Then 1.5.9, please. Thank you.

**Comment by timonf** [comment]
Hi @viennt,

I finally added changelog entries for plugin version 1.5.9 and changed the version in the `composer.json` file. I also move two entries to 1.5.9 that did not exist at the 1.5.8 tag (https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/blob/1.5.8/CHANGELOG_en-GB.md).

Ready to merge and tag :)

**Pull request merged**
